server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.paypal.notification_service.entity"
        spring.json.value.default.type: com.paypal.notification_service.entity.Transaction
